# Generated by Django 2.2.5 on 2019-09-24 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='airport',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
