# Generated by Django 2.2.5 on 2019-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='address',
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
