# Generated by Django 2.2.5 on 2019-09-25 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20190924_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='airport',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only capital letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='cost',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
