# Generated by Django 2.2.5 on 2019-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20190905_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='destinations.Category'),
        ),
    ]
