# Generated by Django 2.2.5 on 2019-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='destinations.Category'),
        ),
    ]
